version: '3'

services:
    mongo:
        container_name: ms_mongo
        image: mongo:latest
        ports: 
            - "27017:27017"
        volumes:
            - "./mongo/db:/data/db"

    nginx:
        build: ./nginx
        container_name: ms_nginx
        depends_on:
            - blogs
            - notification
            - urmg
        ports:
            - "81:81"  

    blogs:
        build: ./blogs
        container_name: ms_blogs
        depends_on:
            - "mongo"
        volumes:
            - "./blogs:/src/app"
        working_dir: "/src/app"
        ports:
            - "5006:5000"       
        command: npm run start   

    notification:
        build: ./notification
        container_name: ms_notification
        depends_on:
            - "mongo"
        volumes:
            - "./notification:/src/app"
        working_dir: "/src/app"
        ports:
            - "5004:5000"       
        command: npm run start  

    urmg:
        build: ./urmg
        container_name: ms_urmg
        depends_on:
            - "mongo"
        volumes:
            - "./urmg:/src/app"
        working_dir: "/src/app"
        ports:
            - "5005:5000"       
        command: npm run start  